### PR TITLE
New commands and upgrades for Alfresco 5.1 compatibility

### PR DESCRIPTION
**Pull request by fsckawk**
alfCreateSite.sh alfDeleteSite.sh alfInviteUser.sh should be tested for compatibility with Alfresco 4.x
Probably they will need minor tweaks...

### CODE REVIEW

**Comment by lutzhorn** [comment]
@fsckawk Thank you very much for this contribution!

**Comment by fsckawk** [comment]
You're welcome!
Next improvements I've planned:
- Move CSRF code to alfToolsLib.sh
- Improve the login/logout process by storing locally the session cookie
- Test with Alfresco 4.x

**Comment by lutzhorn** [comment]
What do you think about using a ticket to authenticate requests? The Share session ID and CSRF handling makes things quite complex.

**Comment by fsckawk** [comment]
Do you mean that it is possible to avoid the need for a new CSRF token for each new request?

I was thinking of an alfLogin.sh script that will get the session ID and store it along with a timestamp in a temporary file. If the session ID is older than an hour, it should be renewed.
The CSRF is a little bit harder. Since you must issue the request twice, probably there should be a function in alfToolLib.sh to handle this operation. Fortunately, there are just three scripts that needs this...

**Pull request merged**
